package com.Artiom.ArtifexAI.PromptOptimization.Model;

public enum PromptType {
    PROMPT_OPTIMIZATION,
    INSTRUCTION_OPTIMIZATION,
    INSTRUCTION_UPDATE,
    SPLASH_ART_GENERATION,
    SPRITE_SHEET_GENERATION,
    IMAGE_EDIT,
    IMAGE_CHANGE_ART_STYLE,
    IMAGE_MASKED_EDIT,
    VIDEO_GENERATION,
    IMAGE_EDIT_HF,
    IMAGE_CHANGE_ART_STYLE_HF,
    SPRITE_SHEET_GENERATION_HF,
    PROMPT_OPTIMIZATION_HF,
    CONTEXT_OPTIMIZATION_HF,
    SPLASH_ART_GENERATION_HF
}
